### ISSUE TITLE
Throws error after setup.

### ISSUE THREAD

**Issue by mhartington** [SevereOverfl0w/deoplete-github#1]
Hi there, so it seems that this throws a lot of errors after setting up.

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/mhartington/.config/nvim/.dein/rplugin/python3/deoplete/deoplete.py", line 47, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/mhartington/.config/nvim/.dein/rplugin/python3/deoplete/deoplete.py", line 81, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/mhartington/.config/nvim/.dein/rplugin/python3/deoplete/deoplete.py", line 138, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/mhartington/.config/nvim/.dein/rplugin/python3/deoplete/sources/github.py", line 67, in gather_candidates
[deoplete]     base = repo_base(self.vim)
[deoplete]   File "/Users/mhartington/.config/nvim/.dein/rplugin/python3/deoplete/sources/github.py", line 25, in repo_base
[deoplete]     base = repo_homepage(vim)
[deoplete]   File "/Users/mhartington/.config/nvim/.dein/rplugin/python3/deoplete/sources/github.py", line 17, in repo_homepage
[deoplete]     homepage = vim.call('rhubarb#homepage_for_url', repo_url)
[deoplete]   File "/usr/local/lib/python3.5/site-packages/neovim/api/nvim.py", line 213, in call
[deoplete]     return self.request('vim_call_function', name, args, **kwargs)
[deoplete]   File "/usr/local/lib/python3.5/site-packages/neovim/api/nvim.py", line 129, in request
[deoplete]     res = self._session.request(name, *args, **kwargs)
[deoplete]   File "/usr/local/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
[deoplete]     raise self.error_wrapper(err)
[deoplete] neovim.api.nvim.NvimError: b'Error calling function.'
[deoplete] An error has occurred. Please execute :messages command.
```

Basic setup derived from the readme 

``` viml
  let g:deoplete#sources = {}
  let g:deoplete#sources.gitcommit=['github']
  let g:deoplete#keyword_patterns = {}
  let g:deoplete#keyword_patterns.gitcommit = '.+'
  let g:deoplete#omni#input_patterns = {}
  let g:deoplete#omni#input_patterns.gitcommit = '.+'
```

Minimal init.vim with vim-plug

```
Plug "shougo/deoplete.nvim"
Plug "SevereOverfl0w/deoplete-github"
call plug#end()


  let g:deoplete#sources = {}
  let g:deoplete#sources.gitcommit=['github']
  let g:deoplete#keyword_patterns = {}
  let g:deoplete#keyword_patterns.gitcommit = '.+'
  let g:deoplete#omni#input_patterns = {}
  let g:deoplete#omni#input_patterns.gitcommit = '.+'
```

**Comment by SevereOverfl0w** [comment]
This plugin depends on both fugitive and rhubarb, by tpope. This perhaps isn't ideal, but I didn't want to replicate work already done.

I've just reviewed the Readme, and I don't think this is clear enough, so I'll make the change when I get the chance.

Thanks for the minimal init.vim, it was really helpful.

---

Generally speaking, this plugin is somewhat, half-done. It works, but it needs to be updated to be defensive and cover edge cases. I'd welcome any PRs to this effect.

**Comment by joaosa** [comment]
I'm thinking it'd be useful to add the remainder of the config to the README. I ended up with startup errors and this helped
